default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: projeto_mvc
  username: postgres
  password: 102030
  host: localhost
  port: 5432

test:
  <<: *default
  database: projeto_mvc_teste
  username: postgres
  password: 102030  
  host: localhost
  port: 5432

